spring:
  datasource:
    druid:
      write:
        url: jdbc:mysql://192.168.219.129:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
      read:
        url: jdbc:mysql://192.168.219.129:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  redis:
    host: 127.0.0.1
    port: 6379
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8


debug: true
server:
  port: 9999
